name: cmo_monitoring

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'The version number of the operator'
          required: true
          default: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG_BASE: 'quay.io/cmo-monitoring-operator-on-z/cmo-monitoring-on-z-operator'
      VERSION: ${{ github.event.inputs.version }}
      PLATFORMS: 'linux/s390x'
      CONTAINER_TOOL: 'docker'

    steps:
    
      - name: Login using gh
        run: gh auth login --hostname github.ibm.com --with-token <<<"${{ secrets.IBM_GITHUB_TOKEN }}"

      - name: Cloning the required repo
        run: |
          mkdir githubActionsTest
          cd githubActionsTest
          gh repo clone ${{ secrets.CMO_REPO_ADD }}
          cd ${{ secrets.CMO_REPO }}
          git checkout new-test-lpar
          cd api/v1alpha1
          ls
      #git checkout .

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.0'

      - name: Run generate and manifests
        working-directory: ./githubActionsTest/${{ secrets.CMO_REPO }}
        run: make generate manifests 

      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Log in to QUAY
        uses: docker/login-action@v2
        with:
           registry: quay.io
           username: ${{ secrets.QUAY_USER }}
           password: ${{ secrets.QUAY_TOKEN }}

      # Builds
      - name: Docker build and push using Buildx
        env:
          IMG: '${{ env.IMAGE_TAG_BASE }}-controller:v$VERSION'
        working-directory: ./githubActionsTest/${{ secrets.CMO_REPO }}
        run: |
          make docker-buildx


      - name: Bundle build and push
        env:
          VERSION: '$VERSION'
          IMG: '${{ env.IMAGE_TAG_BASE }}-controller:v$VERSION'
          BUNDLE_IMG: '${{ env.IMAGE_TAG_BASE }}-bundle:v$VERSION'
        working-directory: ./githubActionsTest/${{ secrets.CMO_REPO }}
        run: |
          make bundle
          sed -e '1 s/\(^FROM\)/FROM --platform=\$\{BUILDPLATFORM\}/; t' -e ' 1,// s//FROM --platform=\$\{BUILDPLATFORM\}/' bundle.Dockerfile > bundle.Dockerfile.cross
          ${{ env.CONTAINER_TOOL }} buildx create --name cmo-monitoring-on-z-operator-builder
          ${{ env.CONTAINER_TOOL }} buildx use cmo-monitoring-on-z-operator-builder
          ${{ env.CONTAINER_TOOL }} buildx build --push --platform=${{ env.PLATFORMS }} --tag ${{ env.BUNDLE_IMG }} -f bundle.Dockerfile.cross .
          ${{ env.CONTAINER_TOOL }} buildx rm cmo-monitoring-on-z-operator-builder
          rm bundle.Dockerfile.cross

          
      - name: Catalog build and push
        env:
          VERSION: '$VERSION'
          DOCKER_DEFAULT_PLATFORM: '${{ env.PLATFORMS }}'
        working-directory: ./githubActionsTest/${{ secrets.CMO_REPO }}
        run: |
          make catalog-build catalog-push


