name: cmo_monitoring

on:
  workflow_dispatch:
    inputs:
        version:
          description: 'The version number of the operator'
          required: true
          default: '0.0.1'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
    
      - name: Login using gh
        run: gh auth login --hostname github.ibm.com --with-token <<<"${{ secrets.IBM_GITHUB_TOKEN }}"

      - name: Cloning the required repo
        run: |
          mkdir githubActionsTest
          cd githubActionsTest
          gh repo clone ${{ secrets.CMO_REPO_ADD }}
          cd ${{ secrets.CMO_REPO }}
          git checkout .

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.0'

      - name: Run generate and manifests
        working-directory: ./githubActionsTest/${{ secrets.CMO_REPO }}
        run: make generate manifests 

      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
          
      - name: Log in to QUAY
        uses: docker/login-action@v2
        with:
           registry: quay.io
           username: ${{ secrets.QUAY_USER }}
           password: ${{ secrets.QUAY_TOKEN }}


      - name: Docker build and push
        working-directory: ./githubActionsTest/${{ secrets.CMO_REPO }}
        run: |
          export IMAGE_TAG_BASE=quay.io/cmo-monitoring-operator-on-z/cmo-monitoring-on-z-operator
          export IMG=quay.io/cmo-monitoring-operator-on-z/cmo-monitoring-on-z-controller
          export PLATFORMS=linux/s390x
          export VERSION=$VERSION
          make docker-buildx
          make bundle bundle-build bundle-push
