name: zvm_workflow

on:
  workflow_dispatch:
    inputs:
      pushBaseImage:
        description: 'whether to push the base image as well to docker or not'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        
      - name: Login using gh
        run: gh auth login --hostname github.ibm.com --with-token <<<"${{ secrets.IBM_GITHUB_TOKEN }}"
        
      - name: Cloning the required repo
        run: |
          mkdir githubActionsTest
          cd githubActionsTest
          gh repo clone ${{ secrets.ZVM_REPO_ADD }}
          cd ${{ secrets.REPO }}
          git checkout .
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
           registry: quay.io
           username: ${{ secrets.QUAY_USER }}
           password: ${{ secrets.QUAY_TOKEN }}
           
      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Push the base docker image depending on the input
        if: ${{ github.event.inputs.pushBaseImage == 'true' }}
        uses: docker/build-push-action@v4
        with:
          platforms: linux/s390x
          file: ./githubActionsTest/${{ secrets.REPO }}/build/artifacts/Dockerfile.base
          context: ./githubActionsTest/${{ secrets.REPO }}//build/scripts/
          push: true
          load: true
          tags: |
            quay.io/cmo-monitoring-operator-on-z/zvm_hyptop_base_image:${{ env.SHORT_SHA }}
            quay.io/cmo-monitoring-operator-on-z/zvm_hyptop_base_image:latest
      
      - name: Build Docker Pre-requites image
        if: ${{ github.event.inputs.pushBaseImage == 'false' }}
        uses: docker/build-push-action@v4
        with:
          file: ./githubActionsTest/${{ secrets.REPO }}/build/artifacts/Dockerfile.base
          context: ./githubActionsTest/${{ secrets.REPO }}/build/scripts/
          push: false
          load: true
          tags: zvm_exporter_base_image:latest
          
           
      - name: Build Docker Final image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/s390x
          file: ./githubActionsTest/${{ secrets.REPO }}/build/artifacts/Dockerfile.pexporter
          context: ./githubActionsTest/${{ secrets.REPO }}/
          push: true
          load: true
          tags: |
            quay.io/cmo-monitoring-operator-on-z/zvm_prom_exporter:${{ env.SHORT_SHA }}
            quay.io/cmo-monitoring-operator-on-z/zvm_prom_exporter:latest


     
  
        
